import random

# random.setstate(42)
r = random.random()
print(r)
print(random.random())
print(random.randint(1,10))
print(random.uniform(1,10))
print(random.randrange(1,10))
print(random.choice([1,2,3,4,5]))
print(random.choices([1,2,3,4,5],k=3))
print(random.sample([1,2,3,4,5],k=3))
print(random.shuffle([1,2,3,4,5]))
print(random.seed(0))
# print(random.getstate())
